#!/bin/bash
# ams-publisher daemon
# chkconfig: 345 20 80
# description: ams-publisher daemon
# processname: ams-publisher

. /etc/rc.d/init.d/functions
PROG_NAME="ams-publisher"
DAEMON_PATH="/usr/bin/ams-publisherd"
LOCK_FILE=/var/lock/subsys/$PROG_NAME

case "$1" in
start)
	echo $"Starting $PROG_NAME: "
	msg=$(daemon $DAEMON_PATH -d start)
	retval=$?
	[ $retval -eq 0 ] && touch $LOCK_FILE
	echo $msg
	exit $retval
;;
stop)
	echo $"Stopping $PROG_NAME: "
	msg=$(daemon $DAEMON_PATH -d stop)
	retval=$?
	[ $retval -eq 0 ] && rm -f $LOCK_FILE
	echo $msg
	exit $retval
;;
restart)
	rm -f $LOCK_FILE
	echo $"Restarting $PROG_NAME: "
	msg=$(daemon $DAEMON_PATH -d restart)
	retval=$?
	[ $retval -eq 0 ] && touch $LOCK_FILE
	echo $msg
	exit $retval
;;
status)
	echo $"Status $PROG_NAME: "
	msg=$(daemon $DAEMON_PATH -d status)
	retval=$?
	echo $msg
	exit $retval
;;
*)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
esac

