#!/bin/bash
# ams-publisher daemon
# chkconfig: 345 20 80
# description: ams-publisher daemon
# processname: ams-publisher

. /etc/rc.d/init.d/functions
PROG_NAME="ams-publisher"
DAEMON_PATH="/usr/bin/ams-publisherd"
LOCK_FILE=/var/lock/subsys/$PROG_NAME

function start()
{
	echo $"Starting $PROG_NAME: "
	msg=$(daemon $DAEMON_PATH -d start)
	retval=$?
	[ $retval -eq 0 ] && touch $LOCK_FILE
	echo $msg
	return $retval
}

function stop()
{
	echo $"Stopping $PROG_NAME: "
	msg=$(daemon $DAEMON_PATH -d stop)
	retval=$?
	[ $retval -eq 0 ] && rm -f $LOCK_FILE
	echo $msg
	return $retval
}

function restart()
{
	rm -f $LOCK_FILE
	echo $"Restarting $PROG_NAME: "
	msg=$(daemon $DAEMON_PATH -d restart)
	retval=$?
	[ $retval -eq 0 ] && touch $LOCK_FILE
	echo $msg
	return $retval
}

function status()
{
	echo $"Status $PROG_NAME: "
	msg=$(daemon $DAEMON_PATH -d status)
	retval=$?
	echo $msg
	return $retval
}

case "$1" in
start)
    start
		retval=$?
		exit $retval
;;
stop)
		stop
		retval=$?
		exit $retval
;;
restart)
    restart
		retval=$?
		exit $retval
;;
condrestart)
	status
	retval=$?
	if (( $retval == 0 ))
  then
      restart
  fi
;;
status)
    status
;;
*)
	echo "Usage: $0 {start|stop|restart|status|condrestart}"
	exit 1
esac

